[git setting ref url](http://qiita.com/azusanakano/items/8dc1d7e384b00239d4d9)

In [1]:
# coding: UTF-8
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

# Series

In [4]:
obj = Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']

-5

In [10]:
obj2['d'] = 6

In [11]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [12]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [13]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [14]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [15]:
'b' in obj2

True

In [16]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [17]:
obj3 = Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [18]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [22]:
obj4.name = 'poplation'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: poplation, dtype: float64

In [23]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

# DataFrame

In [24]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year': [2000,2001,2002,2001,2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [25]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [26]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                  index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [27]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [28]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [29]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [30]:
frame2['debt']=16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [31]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [32]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [33]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [34]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [35]:
'year' in frame2.columns

True

In [36]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [37]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [38]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [39]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [40]:
frame4 = frame2.drop('pop', axis=1)
frame4

year   state  debt
one    2000    Ohio   NaN
two    2001    Ohio  -1.2
three  2002    Ohio   NaN
four   2001  Nevada  -1.5
five   2002  Nevada  -1.7

In [41]:
f = lambda x: x.max() - x.min()

In [42]:
frame2[['year', 'debt']].apply(f)

year    2.0
debt    0.5
dtype: float64

In [43]:
frame2[['year', 'debt']].apply(f, axis=1)

one         0.0
two      2002.2
three       0.0
four     2002.5
five     2003.7
dtype: float64

In [44]:
df = DataFrame({'a':range(7), 'b': range(7, 0, -1),
               'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
               'd':[0,1,2,0,1,2,3]})
df

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [45]:
df2 = df.set_index(['c', 'd'])
df2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [46]:
df.set_index(['c', 'd'], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [47]:
df2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [48]:
df1 = DataFrame({'key':['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                'data1':range(7)})
df2 = DataFrame({'key':['a', 'b', 'd'],
                'data2': range(3)})

In [49]:
df1, df2

(   data1 key
 0      0   b
 1      1   b
 2      2   a
 3      3   c
 4      4   a
 5      5   a
 6      6   b,    data2 key
 0      0   a
 1      1   b
 2      2   d)

In [50]:
pd.merge(df1, df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [51]:
pd.merge(df1, df2, on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [52]:
df3 = DataFrame({'lkey':['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                'data1':range(7)})
df4 = DataFrame({'rkey':['a', 'b', 'd'],
                'data2': range(3)})

In [53]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [54]:
pd.merge(df1, df2, how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [55]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [57]:
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])
s2

c    2
d    3
e    4
dtype: int64

In [58]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [59]:
pd.concat([s1, s2, s3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [60]:
df = DataFrame({'a':range(7), 'b': range(7, 0, -1),
               'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
               'd':[0,1,2,0,1,2,3]})
df

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [61]:
c = df[['c', 'd']]
c

c  d
0  one  0
1  one  1
2  one  2
3  two  0
4  two  1
5  two  2
6  two  3

In [62]:
c2 = c.drop_duplicates(['c'])[['c']].values.flatten()
c2[1]

'two'

In [63]:
c['c'][1]

'one'

# DataFrameの構造変換
[https://openbook4.me/projects/183/sections/1369](https://openbook4.me/projects/183/sections/1369)  

In [2]:
frame = DataFrame({'id': [1, 2, 4, 5, 65, 9],
       'name': ['device1','device2','device3','device6','device3', 'device10'],
        'lat3': [1.5, 1.7, 3.6, 2.4, 3.6, 3.6],
        'lng3':[2.3, 2.3, 1.4, 1.2, 1.4, 1.4]})
frame

id  lat3  lng3      name
0   1   1.5   2.3   device1
1   2   1.7   2.3   device2
2   4   3.6   1.4   device3
3   5   2.4   1.2   device6
4  65   3.6   1.4   device3
5   9   3.6   1.4  device10

In [3]:
index = frame[['lat3', 'lng3']].drop_duplicates().reset_index().set_index(['lat3', 'lng3'])
index

index
lat3 lng3       
1.5  2.3       0
1.7  2.3       1
3.6  1.4       2
2.4  1.2       3

In [4]:
id2 = index.unstack()
id2

index          
lng3   1.2  1.4  2.3
lat3                
1.5    NaN  NaN  0.0
1.7    NaN  NaN  1.0
2.4    3.0  NaN  NaN
3.6    NaN  2.0  NaN

In [5]:
ind_frame = frame.set_index(['lat3', 'lng3'])
ind_frame

id      name
lat3 lng3              
1.5  2.3    1   device1
1.7  2.3    2   device2
3.6  1.4    4   device3
2.4  1.2    5   device6
3.6  1.4   65   device3
     1.4    9  device10

In [6]:
data = ind_frame.join(index, how='inner')
data

id      name  index
lat3 lng3                     
1.5  2.3    1   device1      0
1.7  2.3    2   device2      1
2.4  1.2    5   device6      3
3.6  1.4    4   device3      2
     1.4   65   device3      2
     1.4    9  device10      2

In [7]:
g = data.groupby(['index', 'name'])['id'].count().unstack().fillna(0)
g

name   device1  device10  device2  device3  device6
index                                              
0          1.0       0.0      0.0      0.0      0.0
1          0.0       0.0      1.0      0.0      0.0
2          0.0       1.0      0.0      2.0      0.0
3          0.0       0.0      0.0      0.0      1.0

In [8]:
g1 = data.groupby(['index', 'name']).max()
g1

id
index name        
0     device1    1
1     device2    2
2     device10   9
      device3   65
3     device6    5

In [9]:
g1.unstack()

id                                 
name  device1 device10 device2 device3 device6
index                                         
0         1.0      NaN     NaN     NaN     NaN
1         NaN      NaN     2.0     NaN     NaN
2         NaN      9.0     NaN    65.0     NaN
3         NaN      NaN     NaN     NaN     5.0

### binning

In [78]:
ages = [20, 22, 25, 27, 21, 23, 37, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

In [79]:
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (35, 60], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 11
Categories (4, object): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [80]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 3, 2, 2, 1], dtype=int8)

In [81]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     2
(60, 100]    1
dtype: int64

In [82]:
group_names = ['Youth', 'YungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YungAdult, Youth, ..., MiddleAged, Senior, MiddleAged, MiddleAged, YungAdult]
Length: 11
Categories (4, object): [Youth < YungAdult < MiddleAged < Senior]

In [83]:
g.plot()

In [10]:
f22 = frame[['id', 'lat3', 'lng3']].set_index(['id']).apply(lambda f: f / sum(f), axis=1)
f22

lat3      lng3
id                    
1   0.394737  0.605263
2   0.425000  0.575000
4   0.720000  0.280000
5   0.666667  0.333333
65  0.720000  0.280000
9   0.720000  0.280000

In [11]:
frame

id  lat3  lng3      name
0   1   1.5   2.3   device1
1   2   1.7   2.3   device2
2   4   3.6   1.4   device3
3   5   2.4   1.2   device6
4  65   3.6   1.4   device3
5   9   3.6   1.4  device10

In [12]:
#pd.pivot_table
framep = pd.pivot_table(frame,
                       index=['id'],
                       columns=['name'],
                       values=['lat3'],
                       fill_value=0)
framep

lat3                                 
name device1 device10 device2 device3 device6
id                                           
1        1.5      0.0     0.0     0.0     0.0
2        0.0      0.0     1.7     0.0     0.0
4        0.0      0.0     0.0     3.6     0.0
5        0.0      0.0     0.0     0.0     2.4
9        0.0      3.6     0.0     0.0     0.0
65       0.0      0.0     0.0     3.6     0.0

In [13]:
framep.columns

MultiIndex(levels=[['lat3'], ['device1', 'device10', 'device2', 'device3', 'device6']],
           labels=[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4]],
           names=[None, 'name'])

In [14]:
framep.columns.levels[1]
framep.columns = framep.columns.levels[1]
framep

name  device1  device10  device2  device3  device6
id                                                
1         1.5       0.0      0.0      0.0      0.0
2         0.0       0.0      1.7      0.0      0.0
4         0.0       0.0      0.0      3.6      0.0
5         0.0       0.0      0.0      0.0      2.4
9         0.0       3.6      0.0      0.0      0.0
65        0.0       0.0      0.0      3.6      0.0

In [15]:
index_frame = frame[['id', 'lng3']].set_index(['id'])
index_frame

lng3
id      
1    2.3
2    2.3
4    1.4
5    1.2
65   1.4
9    1.4

In [16]:
framej = index_frame.join(framep, how='left')
framej

lng3  device1  device10  device2  device3  device6
id                                                    
1    2.3      1.5       0.0      0.0      0.0      0.0
2    2.3      0.0       0.0      1.7      0.0      0.0
4    1.4      0.0       0.0      0.0      3.6      0.0
5    1.2      0.0       0.0      0.0      0.0      2.4
65   1.4      0.0       0.0      0.0      3.6      0.0
9    1.4      0.0       3.6      0.0      0.0      0.0

In [17]:
frame.set_index(['id']).index

Int64Index([1, 2, 4, 5, 65, 9], dtype='int64', name='id')

In [18]:
dy = frame[['id']].values.reshape(1, -1)[0]
dy

array([ 1,  2,  4,  5, 65,  9])

In [21]:
indexer = framej.sum(axis=1) >= 4.0
indexer

id
1     False
2      True
4      True
5     False
65     True
9      True
dtype: bool

In [23]:
framej[indexer]

lng3  device1  device10  device2  device3  device6
id                                                    
2    2.3      0.0       0.0      1.7      0.0      0.0
4    1.4      0.0       0.0      0.0      3.6      0.0
65   1.4      0.0       0.0      0.0      3.6      0.0
9    1.4      0.0       3.6      0.0      0.0      0.0

In [27]:
fsum = framej.sum(axis=1) > np.average(framej.sum(axis=1).values)
fsum

id
1     False
2     False
4      True
5     False
65     True
9      True
dtype: bool