[git setting ref url](http://qiita.com/azusanakano/items/8dc1d7e384b00239d4d9)

In [21]:
# coding: UTF-8
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [2]:
obj = Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']

-5

In [10]:
obj2['d'] = 6

In [11]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [12]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [13]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [17]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [21]:
obj3 = Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [22]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [23]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [27]:
obj4.name = 'poplation'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: poplation, dtype: float64

In [29]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [31]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year': [2000,2001,2002,2001,2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [33]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [34]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                  index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [35]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [36]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [37]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [39]:
frame2['debt']=16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [42]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [43]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [44]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [45]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [47]:
'year' in frame2.columns

True

In [48]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [49]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [50]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [51]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [56]:
frame4 = frame2.drop('pop', axis=1)
frame4

year   state  debt
one    2000    Ohio   NaN
two    2001    Ohio  -1.2
three  2002    Ohio   NaN
four   2001  Nevada  -1.5
five   2002  Nevada  -1.7

In [57]:
f = lambda x: x.max() - x.min()

In [60]:
frame2[['year', 'debt']].apply(f)

year    2.0
debt    0.5
dtype: float64

In [61]:
frame2[['year', 'debt']].apply(f, axis=1)

one         0.0
two      2002.2
three       0.0
four     2002.5
five     2003.7
dtype: float64

In [62]:
df = DataFrame({'a':range(7), 'b': range(7, 0, -1),
               'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
               'd':[0,1,2,0,1,2,3]})
df

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [63]:
df2 = df.set_index(['c', 'd'])
df2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [64]:
df.set_index(['c', 'd'], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [65]:
df2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [67]:
df1 = DataFrame({'key':['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                'data1':range(7)})
df2 = DataFrame({'key':['a', 'b', 'd'],
                'data2': range(3)})

In [68]:
df1, df2

(   data1 key
 0      0   b
 1      1   b
 2      2   a
 3      3   c
 4      4   a
 5      5   a
 6      6   b,    data2 key
 0      0   a
 1      1   b
 2      2   d)

In [69]:
pd.merge(df1, df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [70]:
pd.merge(df1, df2, on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [72]:
df3 = DataFrame({'lkey':['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                'data1':range(7)})
df4 = DataFrame({'rkey':['a', 'b', 'd'],
                'data2': range(3)})

In [73]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [74]:
pd.merge(df1, df2, how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [75]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [81]:
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])
s2

c    2
d    3
e    4
dtype: int64

In [80]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [82]:
pd.concat([s1, s2, s3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [3]:
df = DataFrame({'a':range(7), 'b': range(7, 0, -1),
               'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
               'd':[0,1,2,0,1,2,3]})
df

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [30]:
c = df[['c', 'd']]
c

c  d
0  one  0
1  one  1
2  one  2
3  two  0
4  two  1
5  two  2
6  two  3

In [31]:
c2 = c.drop_duplicates(['c'])[['c']].values.flatten()
c2[1]

'two'

In [37]:
c['c'][1]

'one'

# DataFrameの構造変換
別のやり方考えたい  
[https://openbook4.me/projects/183/sections/1369](https://openbook4.me/projects/183/sections/1369)  
  
必要な列だけ抜き出して転置、マージとか可能？
それとも必要ないのか・・・

In [46]:
data = []
for w in c2:
    hoge = []
    for c1, d1 in zip(c['c'], c['d']):
        print(c1)
        if w == c1:
            hoge.append(d1)
        else:
            hoge.append(0)
    data.append(hoge)
data

one
one
one
two
two
two
two
one
one
one
two
two
two
two


[[0, 1, 2, 0, 0, 0, 0], [0, 0, 0, 0, 1, 2, 3]]

In [2]:
df = DataFrame(np.random.randn(7, 3))

In [4]:
df.ix[:4, 1] = 'NA'

In [5]:
df

0         1         2
0 -0.211570        NA -0.634947
1 -0.483193        NA  0.744138
2 -0.499976        NA -0.979478
3 -0.955073        NA -1.633476
4  1.373071        NA -1.143453
5  0.231200 -0.495914  0.091415
6 -0.194845  -1.18469  0.845676

In [7]:
df.fillna(0)
_ = df.fillna(0, inplace=True)

In [8]:
df

0         1         2
0 -0.211570        NA -0.634947
1 -0.483193        NA  0.744138
2 -0.499976        NA -0.979478
3 -0.955073        NA -1.633476
4  1.373071        NA -1.143453
5  0.231200 -0.495914  0.091415
6 -0.194845  -1.18469  0.845676

In [94]:
frame = DataFrame({'id': [1, 2, 4, 5, 65, 9],
       'name': ['device1','device2','device3','device6','device3', 'device10'],
        'lat3': [1.5, 1.7, 3.6, 2.4, 3.6, 3.6],
        'lng3':[2.3, 2.3, 1.4, 1.2, 1.4, 1.4]})
frame

id  lat3  lng3      name
0   1   1.5   2.3   device1
1   2   1.7   2.3   device2
2   4   3.6   1.4   device3
3   5   2.4   1.2   device6
4  65   3.6   1.4   device3
5   9   3.6   1.4  device10

In [95]:
index = frame[['lat3', 'lng3']].drop_duplicates().reset_index().set_index(['lat3', 'lng3'])
index

index
lat3 lng3       
1.5  2.3       0
1.7  2.3       1
3.6  1.4       2
2.4  1.2       3

In [96]:
ind_frame = frame.set_index(['lat3', 'lng3'])
ind_frame

id      name
lat3 lng3              
1.5  2.3    1   device1
1.7  2.3    2   device2
3.6  1.4    4   device3
2.4  1.2    5   device6
3.6  1.4   65   device3
     1.4    9  device10

In [97]:
data = ind_frame.join(index, how='inner')
data

id      name  index
lat3 lng3                     
1.5  2.3    1   device1      0
1.7  2.3    2   device2      1
2.4  1.2    5   device6      3
3.6  1.4    4   device3      2
     1.4   65   device3      2
     1.4    9  device10      2

In [98]:
g = data.groupby(['index', 'name'])['id'].count().unstack().fillna(0)
g

name   device1  device10  device2  device3  device6
index                                              
0          1.0       0.0      0.0      0.0      0.0
1          0.0       0.0      1.0      0.0      0.0
2          0.0       1.0      0.0      2.0      0.0
3          0.0       0.0      0.0      0.0      1.0